server:
    port: 15601
spring:
    thymeleaf:
        cache: false
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    datasource:
        driver-class-name:  net.sf.log4jdbc.DriverSpy
        url:                jdbc:log4jdbc:oracle:thin:@localhost:49161:xe
        username:           HR
        password:           HR
        schema:             HR
    rabbitmq:
        addresses: localhost:5672,localhost:5673,localhost:5674
        username: guest
        password: guest
        virtual-host: /
dlq:
    rabbitmq:
        dead-letter-queue:
          error.queue: backup.on.delete.queue
          error.queue2: backup.on.delete.queue2
          null.queue:
        max-count: 500
logging:
    level:
        rabbitmq.console: DEBUG
        org.springframework.web.client.RestTemplate: INFO
        jdbc.connection: INFO
        jdbc.sqltiming: INFO
        jdbc.audit: OFF
        jdbc.resultset: OFF
        jdbc.sqlonly: OFF

